-- AlterTable
ALTER TABLE "Issue" ADD COLUMN "devExclusivo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Issue" ADD COLUMN "pge" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Issue" ADD COLUMN "conversao" BOOLEAN NOT NULL DEFAULT false;
